import { Game } from '@/data/games';

const categoryTemplates: Record<string, string[]> = {
  Arcade: [
    'Looking for an exciting arcade adventure? {name} brings the classic arcade experience right to your browser with vibrant visuals and addictive gameplay. Whether you are a casual gamer or a hardcore enthusiast, this game delivers non-stop fun with its intuitive controls and engaging mechanics. The challenge escalates as you progress, keeping you hooked for hours. No downloads required — just open and play instantly on any device. Perfect for quick gaming sessions or marathon play, {name} is the ultimate way to unwind and have fun online.',
    '{name} is one of the best arcade games available online today. Featuring smooth animations, responsive controls, and a rewarding progression system, this game stands out from typical browser-based entertainment. Each level introduces new challenges that test your reflexes and strategic thinking. With its vibrant art style and satisfying sound effects, you will feel fully immersed in the gaming world. Play now on Cool2Fun and discover why thousands of players keep coming back for more arcade action.',
  ],
  Action: [
    '{name} delivers intense action-packed gameplay that will get your adrenaline pumping. Battle through challenging levels, master your timing, and outsmart your opponents in this fast-paced online adventure. The game combines fluid mechanics with spectacular visuals to create an unforgettable experience. Every moment counts as you react quickly and make split-second decisions. Available instantly in your browser — no installation or sign-up needed. Join the community of gamers who have already discovered this thrilling title.',
    'Get ready for non-stop action with {name}! This browser-based game offers heart-racing challenges that push your skills to the limit. Featuring dynamic gameplay, responsive controls, and impressive visuals, it has become a favorite among online gamers worldwide. The difficulty scales smoothly, keeping beginners engaged while offering seasoned players a real challenge. Whether you have five minutes or an hour, {name} fits perfectly into your schedule. Start playing right now on Cool2Fun and prove your skills!',
  ],
  Racing: [
    '{name} brings the thrill of racing directly to your browser without any downloads. Feel the speed, master the tracks, and compete against challenging opponents in this high-octane racing experience. Every turn requires precision, and every straight demands full throttle. The stunning visuals and realistic physics make you forget you are playing a free browser game. Customize your vehicle, improve your times, and climb the leaderboards. Cool2Fun hosts this incredible racing title so you can enjoy premium gameplay whenever and wherever you want.',
    'Speed junkies, this one is for you! {name} is a free online racing game that delivers genuine excitement without the need for downloads or premium hardware. Navigate through winding tracks, dodge obstacles, and perfect your racing lines to shave precious seconds off your best times. The intuitive control scheme means anyone can pick it up and start playing immediately. With regular updates and fresh content, the fun never ends. Rev your engines and visit Cool2Fun to start racing today!',
  ],
  Sports: [
    'Sports fans rejoice — {name} brings authentic sports action to your browser with impressive gameplay depth. Whether you are a lifelong fan or a casual player, the accessible mechanics ensure everyone can join the fun. Compete against AI opponents or challenge your friends in intense matches that test your reflexes and tactics. The realistic physics engine adds credibility to every kick, throw, and sprint. Play this free browser game instantly on Cool2Fun and show the world your athletic prowess. No downloads, no fees — just pure sports entertainment.',
    'Calling all sports enthusiasts! {name} is a free browser game that captures the excitement of real sports competition. Featuring smooth animations, intelligent AI opponents, and a variety of game modes, it offers replayability that keeps you coming back. Master the basics, develop your own strategies, and climb through the rankings. The game runs seamlessly on both desktop and mobile browsers. Head to Cool2Fun now, select your team, and step onto the virtual field for an unforgettable sports gaming experience.',
  ],
  Adventure: [
    '{name} is an epic adventure game you can play right in your browser for free. Embark on a journey through imaginative worlds, solve intricate puzzles, and overcome cunning obstacles along the way. The rich storytelling and detailed environments create a truly immersive experience that goes beyond typical browser gaming. Every decision you make shapes your adventure, providing a personalized narrative that changes with each playthrough. The game strikes a perfect balance between accessibility and depth. Start your adventure now on Cool2Fun and lose yourself in an unforgettable quest.',
    'Ready for an adventure? {name} is a free browser-based game that combines exploration, puzzle-solving, and storytelling into one captivating experience. Navigate through beautifully crafted levels, discover hidden secrets, and unlock new abilities as you progress through the story. The intuitive controls make it easy for players of all skill levels to dive right in and start exploring. With its charming art direction and satisfying progression system, this game is a must-play for any adventure fan. Play now on Cool2Fun and begin your journey.',
  ],
  Puzzle: [
    '{name} is a brain-teasing puzzle game that sharpens your mind while providing hours of entertainment. Each level presents unique challenges that require creative thinking, pattern recognition, and strategic planning to solve. The clean interface and relaxing soundtrack create the perfect environment for focused gameplay. Difficulty ramps up gradually, ensuring you never feel overwhelmed but always feel challenged. Whether you have a few minutes between classes or a full evening at home, this puzzle game adapts to your schedule. Challenge yourself on Cool2Fun and see how far your logic can take you.',
    'Exercise your brain with {name} — a free online puzzle game available instantly in your browser. Featuring hundreds of handcrafted levels, each puzzle offers a fresh challenge that tests different cognitive skills. The satisfying "aha!" moment when you crack a tough level keeps the gameplay loop incredibly rewarding. Minimalist visuals keep the focus on pure logic, while subtle animations add polish without distraction. No downloads or sign-ups needed. Visit Cool2Fun, load up {name}, and give your brain the workout it deserves.',
  ],
  Simulation: [
    '{name} offers a deep simulation experience directly in your web browser. Build, manage, and grow your virtual world with intuitive controls and powerful simulation mechanics. Whether you are running an empire, nurturing a ecosystem, or mastering complex systems, this game provides satisfying depth without overwhelming complexity. Watch your decisions ripple through the simulation in real time. The addictive loop of trying, failing, and improving keeps you engaged for sessions that last much longer than planned. Start building your simulation on Cool2Fun today.',
    'Experience the joy of management and growth with {name}, a free browser simulation game. Develop strategies, allocate resources wisely, and see your virtual creation flourish under your guidance. The game strikes a compelling balance between accessibility and strategic depth, making it enjoyable for both simulation veterans and newcomers. With its satisfying progression curve and endless replayability, every session feels fresh. No installation required — just open your browser and dive into the simulation. Check out this gem on Cool2Fun and start your journey.',
  ],
  Shooting: [
    '{name} delivers intense shooting action straight to your browser with zero downloads required. Lock and load as you take on challenging missions across a variety of vibrant environments. The responsive controls and tight aiming mechanics make every shot feel precise and impactful. Engage with smart AI opponents that adapt to your tactics, keeping every encounter unpredictable and exciting. The satisfying feedback from landing hits and completing objectives creates an addictive gameplay loop. Grab your gear and head to Cool2Fun to experience top-tier browser shooting games.',
    'Aim, fire, win — {name} is a free browser shooting game that packs serious action into a lightweight package. Featuring multiple game modes, a variety of weapons, and smooth performance, it rivals many premium shooters. The intuitive controls make aiming and shooting feel natural on both desktop and mobile devices. Fast matchmaking means you spend less time waiting and more time shooting. Cool2Fun hosts this title for free, so you can jump into the action instantly. Are you ready to prove yourself on the battlefield?',
  ],
  Fighting: [
    '{name} brings the intensity of fighting games to your browser with stunning moves and competitive gameplay. Master combos, time your attacks perfectly, and defeat opponents in thrilling battles that test your reflexes and strategy. The roster of unique characters offers diverse playstyles, ensuring every fighter finds their perfect match. Smooth animations and impactful hit effects make every punch, kick, and special move feel satisfying. Play against challenging AI or challenge a friend in local multiplayer. Visit Cool2Fun and step into the arena for free.',
    'Enter the ring with {name} — a free browser fighting game that delivers knockout entertainment. Execute powerful combos, dodge incoming attacks, and use your environment to gain the upper hand in intense battles. The intuitive control scheme makes it accessible for beginners while offering enough depth for competitive players to master. Regular updates introduce new characters and content, keeping the experience fresh and exciting. No downloads, no fees — just pure fighting action in your browser. Start your training on Cool2Fun today.',
  ],
  Strategy: [
    '{name} is a strategic browser game that challenges your tactical thinking and resource management skills. Plan your moves carefully, adapt to changing conditions, and outmaneuver your opponents through superior strategy. The deep gameplay systems reward careful planning over reflexive reactions, creating a uniquely satisfying strategic experience. Multiple difficulty levels and game modes provide replayability that scales with your skill. The clean interface keeps all the information you need clearly visible. Deploy your strategies on Cool2Fun and conquer every challenge that awaits.',
    'Strategic minds unite — {name} is a free online strategy game available instantly in your browser. Build your forces, research new technologies, and execute brilliant tactics to dominate your opponents. The game offers a rich strategic layer that rewards long-term planning and quick adaptation. Whether you prefer defensive play or aggressive expansion, the flexible mechanics accommodate your preferred style. Smooth performance on any modern browser means no downloads or hardware headaches. Plan your victory on Cool2Fun and become the ultimate strategist.',
  ],
};

const genericTemplates = [
  '{name} is a fantastic free online game you can play right now on Cool2Fun. Featuring engaging gameplay, polished visuals, and intuitive controls, it has quickly become a favorite among gamers of all ages. The developers have crafted an experience that is both accessible for beginners and challenging enough to keep experienced players coming back for more. New levels and content are added regularly, ensuring the fun never gets stale. Best of all, it runs directly in your browser with no downloads or sign-ups required. Open any device, visit Cool2Fun, and start playing {name} today!',
  'If you are looking for a fun way to pass the time, {name} is the perfect choice. This free browser game combines accessible gameplay with enough depth to keep you engaged for hours on end. The colorful graphics and smooth animations create an inviting atmosphere that makes you want to keep playing. Simple controls mean you can jump right in without any learning curve, while the challenging levels provide a satisfying sense of progression. Cool2Fun hosts this amazing game for free, so you can start playing instantly without any downloads or registration.',
];

function getTemplatesForCategory(cats: string[]): string[] {
  for (const cat of cats) {
    if (categoryTemplates[cat]) return categoryTemplates[cat];
  }
  return genericTemplates;
}

export function generateSpinContent(game: Game): string {
  const templates = getTemplatesForCategory(game.cat);
  const template = templates[Math.floor(Math.random() * templates.length)];
  return template.replace(/{name}/g, game.name);
}
