window.GAMES = [
  // ── TOP GAMES ─────────────────────────────────────────────
  { slug:"slope",                      name:"Slope",                        cat:["Arcade","Action"],             desc:"Endless ball runner on a neon slope",              src:"games/slope/index.html" },
  { slug:"subway-surfers",             name:"Subway Surfers",               cat:["Action","Arcade"],             desc:"Classic endless rail runner",                      src:"https://ubg98.github.io/SubwaySurfers/" },
  { slug:"run-3",                      name:"Run 3",                        cat:["Action","Arcade"],             desc:"Run through endless space tunnels",                src:"https://ubg98.github.io/Run3/" },
  { slug:"retro-bowl",                 name:"Retro Bowl",                   cat:["Sports","Simulation"],         desc:"Old-school American football simulation",           src:"games/rb/index.html" },
  { slug:"drive-mad",                  name:"Drive Mad",                    cat:["Racing","Action"],             desc:"Physics-based driving challenge",                  src:"https://ubg98.github.io/DriveMad/" },
  { slug:"monkey-mart",                name:"Monkey Mart",                  cat:["Simulation","Adventure"],      desc:"Run your own monkey supermarket",                  src:"https://ubg98.github.io/MonkeyMart/" },
  { slug:"geometry-dash",              name:"Geometry Dash",                cat:["Action","Arcade"],             desc:"Tap to the beat in this rhythm platformer",        src:"https://ubg98.github.io/GeometryDash/" },
  { slug:"super-mario-wonder",         name:"Super Mario Wonder",           cat:["Arcade","Adventure"],          desc:"Platform adventure with Mario",                    src:"https://ubg98.github.io/SuperMario/" },
  { slug:"fireboy-and-watergirl",      name:"Fireboy and Watergirl",        cat:["Adventure","Puzzle"],          desc:"2-player elemental puzzle platformer",             src:"https://ubg98.github.io/FireboyWatergirl/" },
  { slug:"moto-x3m",                   name:"Moto X3M",                     cat:["Racing","Action"],             desc:"Extreme motorcycle stunt racing",                  src:"https://ubg98.github.io/MotoX3M/" },

  // ── ACTION ────────────────────────────────────────────────
  { slug:"iron-snout",                 name:"Iron Snout",                   cat:["Fighting","Action"],           desc:"Pig vs wolves fighting action",                    src:"https://ubg98.github.io/IronSnout/" },
  { slug:"rooftop-snipers",            name:"Rooftop Snipers",              cat:["Action","Shooting"],           desc:"2-player rooftop sniping duel",                    src:"https://ubg98.github.io/RooftopSnipers/" },
  { slug:"stick-merge-2",              name:"Stick Merge 2",                cat:["Action","Shooting"],           desc:"Merge weapons and shoot enemies",                  src:"https://ubg98.github.io/StickMerge2/" },
  { slug:"rusher-crusher",             name:"Rusher Crusher",               cat:["Action","Racing"],             desc:"Smash cars in this action driver",                 src:"https://ubg98.github.io/RusherCrusher/" },
  { slug:"stickman-hook",              name:"Stickman Hook",                cat:["Action","Arcade"],             desc:"Swing like Spiderman on a hook",                   src:"https://ubg98.github.io/StickmanHook/" },
  { slug:"stickman-fighter-epic-battles", name:"Stickman Fighter",          cat:["Action","Fighting"],           desc:"Epic stickman battle action",                      src:"https://ubg98.github.io/StickmanFighter/" },
  { slug:"apple-shooter",              name:"Apple Shooter",                cat:["Action","Shooting"],           desc:"Shoot the apple off your friend's head",           src:"https://ubg98.github.io/AppleShooter/" },
  { slug:"dead-again",                 name:"Dead Again",                   cat:["Action","Shooting"],           desc:"Survive waves of zombies",                         src:"https://ubg98.github.io/DeadAgain/" },
  { slug:"tunnel-rush-2",              name:"Tunnel Rush 2",                cat:["Action","Arcade"],             desc:"Fly through neon tunnels at high speed",           src:"https://ubg98.github.io/TunnelRush2/" },
  { slug:"get-on-top",                 name:"Get On Top",                   cat:["Action","Sports"],             desc:"Push your opponent off the platform",              src:"https://ubg98.github.io/GetOnTop/" },
  { slug:"tag-unblocked",              name:"Tag",                          cat:["Action"],                      desc:"Multiplayer tag game",                             src:"https://ubg98.github.io/Tag/" },
  { slug:"hanger",                     name:"Hanger",                       cat:["Action","Arcade"],             desc:"Swing through levels on a rope",                   src:"https://ubg98.github.io/Hanger/" },
  { slug:"fruit-ninja",                name:"Fruit Ninja",                  cat:["Action","Arcade"],             desc:"Slice falling fruit with your blade",              src:"https://ubg98.github.io/FruitNinja/" },
  { slug:"friday-night-funkin",        name:"Friday Night Funkin",          cat:["Action","Arcade"],             desc:"Rhythm battle music game",                         src:"https://ubg98.github.io/FridayNightFunkin/" },

  // ── RACING ────────────────────────────────────────────────
  { slug:"moto-x3m-2",                 name:"Moto X3M 2",                   cat:["Racing","Action"],             desc:"More extreme moto stunt levels",                   src:"https://ubg98.github.io/MotoX3M2/" },
  { slug:"moto-x3m-4-winter",          name:"Moto X3M Winter",              cat:["Racing","Action"],             desc:"Icy winter moto stunt racing",                     src:"https://ubg98.github.io/MotoX3M4/" },
  { slug:"moto-x3m-5-pool-party",      name:"Moto X3M Pool Party",          cat:["Racing","Action"],             desc:"Pool party moto stunt madness",                    src:"https://ubg98.github.io/MotoX3M5/" },
  { slug:"moto-x3m-6-spooky-land",     name:"Moto X3M Spooky Land",         cat:["Racing","Action"],             desc:"Halloween moto stunt racing",                      src:"https://ubg98.github.io/MotoX3M6/" },
  { slug:"crazy-cars",                 name:"Crazy Cars",                   cat:["Racing","Arcade"],             desc:"Wild car racing action",                           src:"https://ubg98.github.io/CrazyCars/" },
  { slug:"drift-boss",                 name:"Drift Boss",                   cat:["Racing","Arcade"],             desc:"Tap to drift around corners",                      src:"https://ubg98.github.io/DriftBoss/" },
  { slug:"highway-rider-extreme",      name:"Highway Rider Extreme",        cat:["Racing","Action"],             desc:"Extreme highway motorcycle racing",                src:"https://ubg98.github.io/HighwayRider/" },
  { slug:"neon-racer",                 name:"Neon Racer",                   cat:["Racing","Arcade"],             desc:"Futuristic neon racing game",                      src:"https://ubg98.github.io/NeonRacer/" },
  { slug:"neon-biker",                 name:"Neon Biker",                   cat:["Racing","Action"],             desc:"Neon-lit motorcycle stunts",                       src:"https://ubg98.github.io/NeonBiker/" },
  { slug:"truck-trials",               name:"Truck Trials",                 cat:["Racing","Action"],             desc:"Off-road truck stunt challenge",                   src:"https://ubg98.github.io/TruckTrials/" },
  { slug:"jelly-truck",                name:"Jelly Truck",                  cat:["Racing","Puzzle"],             desc:"Drive a wobbly jelly truck",                       src:"https://ubg98.github.io/JellyTruck/" },
  { slug:"endless-truck",              name:"Endless Truck",                cat:["Racing","Action"],             desc:"Keep your truck going forever",                    src:"https://ubg98.github.io/EndlessTruck/" },
  { slug:"e-scooter",                  name:"E-Scooter",                    cat:["Racing","Arcade"],             desc:"Urban electric scooter racing",                    src:"https://ubg98.github.io/EScooter/" },
  { slug:"eggy-car",                   name:"Eggy Car",                     cat:["Racing","Arcade"],             desc:"Drive carefully with an egg on top",               src:"https://ubg98.github.io/EggyCar/" },

  // ── ADVENTURE & PUZZLE ────────────────────────────────────
  { slug:"fireboy-and-watergirl-2",    name:"Fireboy and Watergirl 2",      cat:["Adventure","Puzzle"],          desc:"Light temple 2-player adventure",                  src:"https://ubg98.github.io/FireboyWatergirl2/" },
  { slug:"fireboy-and-watergirl-3",    name:"Fireboy and Watergirl 3",      cat:["Adventure","Puzzle"],          desc:"Ice temple 2-player adventure",                    src:"https://ubg98.github.io/FireboyWatergirl3/" },
  { slug:"fireboy-and-watergirl-4",    name:"Fireboy and Watergirl 4",      cat:["Adventure","Puzzle"],          desc:"Crystal temple 2-player adventure",                src:"https://ubg98.github.io/FireboyWatergirl4/" },
  { slug:"fireboy-and-watergirl-5",    name:"Fireboy and Watergirl 5",      cat:["Adventure","Puzzle"],          desc:"Elements 2-player adventure",                      src:"https://ubg98.github.io/FireboyWatergirl5/" },
  { slug:"fireboy-and-watergirl-6",    name:"Fireboy and Watergirl 6",      cat:["Adventure","Puzzle"],          desc:"Fairy tales 2-player adventure",                   src:"https://ubg98.github.io/FireboyWatergirl6/" },
  { slug:"3-pandas-in-japan",          name:"3 Pandas In Japan",            cat:["Adventure","Puzzle"],          desc:"Help three pandas escape trouble",                 src:"https://ubg98.github.io/3pandasjapan/" },
  { slug:"adam-and-eve-7",             name:"Adam And Eve 7",               cat:["Adventure","Puzzle"],          desc:"Point and click adventure puzzle",                 src:"https://ubg98.github.io/adameve7/" },
  { slug:"blumgi-slime",               name:"Blumgi Slime",                 cat:["Adventure","Puzzle"],          desc:"Slimy physics puzzle adventure",                   src:"https://ubg98.github.io/BlumgiSlime/" },
  { slug:"bouncy-woods",               name:"Bouncy Woods",                 cat:["Adventure","Puzzle"],          desc:"Bounce through obstacles to escape",               src:"https://ubg98.github.io/BouncyWoods/" },
  { slug:"getting-over-it",            name:"Getting Over It",              cat:["Action","Adventure"],          desc:"Climb with a hammer in this brutal challenge",     src:"https://ubg98.github.io/GettingOverIt/" },
  { slug:"vex-8",                      name:"Vex 8",                        cat:["Adventure","Action"],          desc:"Stickman obstacle platformer",                     src:"https://ubg98.github.io/Vex8/" },
  { slug:"vex-7",                      name:"Vex 7",                        cat:["Adventure","Action"],          desc:"Stickman obstacle platformer 7",                   src:"https://ubg98.github.io/Vex7/" },
  { slug:"vex-6",                      name:"Vex 6",                        cat:["Adventure","Action"],          desc:"Stickman obstacle platformer 6",                   src:"https://ubg98.github.io/Vex6/" },
  { slug:"vex-5",                      name:"Vex 5",                        cat:["Adventure","Action"],          desc:"Stickman obstacle platformer 5",                   src:"https://ubg98.github.io/Vex5/" },
  { slug:"vex-4",                      name:"Vex 4",                        cat:["Adventure","Action"],          desc:"Stickman obstacle platformer 4",                   src:"https://ubg98.github.io/Vex4/" },
  { slug:"vex-3",                      name:"Vex 3",                        cat:["Adventure","Action"],          desc:"Stickman obstacle platformer 3",                   src:"https://ubg98.github.io/Vex3/" },
  { slug:"snail-bob",                  name:"Snail Bob",                    cat:["Adventure","Puzzle"],          desc:"Help Snail Bob find his way home",                 src:"https://ubg98.github.io/SnailBob/" },
  { slug:"snail-bob-2",                name:"Snail Bob 2",                  cat:["Adventure","Puzzle"],          desc:"Snail Bob in a Christmas adventure",               src:"https://ubg98.github.io/SnailBob2/" },
  { slug:"snail-bob-3",                name:"Snail Bob 3",                  cat:["Adventure","Puzzle"],          desc:"Snail Bob in ancient Egypt",                       src:"https://ubg98.github.io/SnailBob3/" },
  { slug:"snail-bob-4",                name:"Snail Bob 4",                  cat:["Adventure","Puzzle"],          desc:"Snail Bob in space",                               src:"https://ubg98.github.io/SnailBob4/" },
  { slug:"snail-bob-5",                name:"Snail Bob 5",                  cat:["Adventure","Puzzle"],          desc:"Snail Bob loves nature",                           src:"https://ubg98.github.io/SnailBob5/" },
  { slug:"snail-bob-6",                name:"Snail Bob 6",                  cat:["Adventure","Puzzle"],          desc:"Snail Bob in a winter wonderland",                 src:"https://ubg98.github.io/SnailBob6/" },
  { slug:"snail-bob-7",                name:"Snail Bob 7",                  cat:["Adventure","Puzzle"],          desc:"Snail Bob goes to fantasy",                        src:"https://ubg98.github.io/SnailBob7/" },
  { slug:"snail-bob-8",                name:"Snail Bob 8",                  cat:["Adventure","Puzzle"],          desc:"Snail Bob in island story",                        src:"https://ubg98.github.io/SnailBob8/" },
  { slug:"wheely-2",                   name:"Wheely 2",                     cat:["Adventure","Puzzle"],          desc:"Help the little red car on its journey",           src:"https://ubg98.github.io/Wheely2/" },
  { slug:"wheely-3",                   name:"Wheely 3",                     cat:["Adventure","Puzzle"],          desc:"Wheely goes to the medieval times",                src:"https://ubg98.github.io/Wheely3/" },
  { slug:"wheely-4",                   name:"Wheely 4",                     cat:["Adventure","Puzzle"],          desc:"Wheely in time",                                   src:"https://ubg98.github.io/Wheely4/" },
  { slug:"wheely-5",                   name:"Wheely 5",                     cat:["Adventure","Puzzle"],          desc:"Wheely the car detective",                         src:"https://ubg98.github.io/Wheely5/" },
  { slug:"wheely-6",                   name:"Wheely 6",                     cat:["Adventure","Puzzle"],          desc:"Wheely in fairyland",                              src:"https://ubg98.github.io/Wheely6/" },
  { slug:"wheely-7",                   name:"Wheely 7",                     cat:["Adventure","Puzzle"],          desc:"Wheely in space",                                  src:"https://ubg98.github.io/Wheely7/" },
  { slug:"wheely-8",                   name:"Wheely 8",                     cat:["Adventure","Puzzle"],          desc:"Wheely in aliens",                                 src:"https://ubg98.github.io/Wheely8/" },
  { slug:"bob-the-robber-2",           name:"Bob The Robber 2",             cat:["Adventure","Puzzle"],          desc:"Sneak past guards and steal treasures",            src:"https://ubg98.github.io/BobTheRobber2/" },
  { slug:"raft-wars",                  name:"Raft Wars",                    cat:["Adventure","Shooting"],        desc:"Defend your treasure on a raft",                   src:"https://ubg98.github.io/RaftWars/" },
  { slug:"raft-wars-2",                name:"Raft Wars 2",                  cat:["Adventure","Shooting"],        desc:"More raft war battles",                            src:"https://ubg98.github.io/RaftWars2/" },

  // ── SPORTS ────────────────────────────────────────────────
  { slug:"boxing-random",              name:"Boxing Random",                cat:["Sports","Fighting"],           desc:"Wacky 2-player boxing game",                       src:"https://ubg98.github.io/BoxingRandom/" },
  { slug:"3d-bowling",                 name:"3D Bowling",                   cat:["Sports"],                      desc:"Realistic 3D bowling experience",                  src:"https://ubg98.github.io/3dbowling/" },
  { slug:"head-soccer-2023",           name:"Head Soccer 2023",             cat:["Sports","Arcade"],             desc:"Big head soccer showdowns",                        src:"https://ubg98.github.io/HeadSoccer2023/" },
  { slug:"heads-arena-soccer-all-stars", name:"Heads Arena Soccer",         cat:["Sports","Action"],             desc:"All-stars big head soccer brawl",                  src:"https://ubg98.github.io/HeadsArenaSoccer/" },
  { slug:"infinite-soccer",            name:"Infinite Soccer",              cat:["Sports","Arcade"],             desc:"Never-ending soccer challenges",                   src:"https://ubg98.github.io/InfiniteSoccer/" },
  { slug:"football-legends",           name:"Football Legends",             cat:["Sports","Action"],             desc:"Legendary football battles",                       src:"https://ubg98.github.io/FootballLegends/" },
  { slug:"football-masters",           name:"Football Masters",             cat:["Sports","Action"],             desc:"Master the beautiful game",                        src:"https://ubg98.github.io/FootballMasters/" },
  { slug:"football-brawl",             name:"Football Brawl",               cat:["Sports","Fighting"],           desc:"Brawl your way to football victory",               src:"https://ubg98.github.io/FootballBrawl/" },
  { slug:"football-strike",            name:"Football Strike",              cat:["Sports","Arcade"],             desc:"Flick and score free kicks",                       src:"https://ubg98.github.io/FootballStrike/" },
  { slug:"penalty-kick-online",        name:"Penalty Kick Online",          cat:["Sports","Arcade"],             desc:"Score and save penalty kicks",                     src:"https://ubg98.github.io/PenaltyKick/" },
  { slug:"basketball-legends",         name:"Basketball Legends",           cat:["Sports","Action"],             desc:"Legendary basketball 1v1 battles",                 src:"https://ubg98.github.io/BasketballLegends/" },
  { slug:"basketball-legends-2020",    name:"Basketball Legends 2020",      cat:["Sports","Action"],             desc:"Updated basketball legends action",                src:"https://ubg98.github.io/BasketballLegends2020/" },
  { slug:"basketball-stars",           name:"Basketball Stars",             cat:["Sports","Action"],             desc:"Multiplayer basketball showdowns",                 src:"https://ubg98.github.io/BasketballStars/" },
  { slug:"basketball-line",            name:"Basketball Line",              cat:["Sports","Puzzle"],             desc:"Draw the path to the basket",                      src:"https://ubg98.github.io/BasketballLine/" },
  { slug:"soccer-heads",               name:"Soccer Heads",                 cat:["Sports","Arcade"],             desc:"Big head soccer 1v1",                              src:"https://ubg98.github.io/SoccerHeads/" },
  { slug:"super-liquid-soccer",        name:"Super Liquid Soccer",          cat:["Sports","Arcade"],             desc:"Liquid physics soccer game",                       src:"https://ubg98.github.io/SuperLiquidSoccer/" },
  { slug:"tap-tap-shots",              name:"Tap Tap Shots",                cat:["Sports","Arcade"],             desc:"Tap to make basketball shots",                     src:"https://ubg98.github.io/TapTapShots/" },
  { slug:"g-switch-4",                 name:"G-Switch 4",                   cat:["Action","Arcade"],             desc:"Gravity-flipping endless runner",                  src:"https://ubg98.github.io/GSwitch4/" },
  { slug:"g-switch-3",                 name:"G-Switch 3",                   cat:["Action","Arcade"],             desc:"Multiplayer gravity runner",                       src:"https://ubg98.github.io/GSwitch3/" },
  { slug:"g-switch-2",                 name:"G-Switch 2",                   cat:["Action","Arcade"],             desc:"2-player gravity runner",                          src:"https://ubg98.github.io/GSwitch2/" },

  // ── PUZZLE & STRATEGY ─────────────────────────────────────
  { slug:"little-alchemy-2",           name:"Little Alchemy 2",             cat:["Puzzle","Simulation"],         desc:"Combine elements to craft the world",              src:"https://ubg98.github.io/LittleAlchemy2/" },
  { slug:"mr-bullet",                  name:"Mr Bullet",                    cat:["Shooting","Puzzle"],           desc:"Clever physics shooting puzzles",                  src:"https://ubg98.github.io/MrBullet/" },
  { slug:"papa-cherry-saga",           name:"Papa Cherry Saga",             cat:["Puzzle"],                      desc:"Sweet match-3 puzzle game",                        src:"https://ubg98.github.io/PapaCherrySaga/" },
  { slug:"ball-sort-halloween",        name:"Ball Sort Halloween",           cat:["Puzzle","Strategy"],           desc:"Halloween-themed color sort puzzle",               src:"https://ubg98.github.io/BallSortHalloween/" },
  { slug:"ball-sort-puzzle",           name:"Ball Sort Puzzle",             cat:["Puzzle","Strategy"],           desc:"Sort colored balls into tubes",                    src:"https://ubg98.github.io/BallSortPuzzle/" },
  { slug:"marbles-sorting",            name:"Marbles Sorting",              cat:["Puzzle","Strategy"],           desc:"Sort colorful marbles into tubes",                 src:"https://ubg98.github.io/MarblesSorting/" },
  { slug:"wordle-unlimited",           name:"Wordle Unlimited",             cat:["Puzzle"],                      desc:"Unlimited word guessing game",                     src:"https://ubg98.github.io/WordleUnlimited/" },
  { slug:"word-slide",                 name:"Word Slide",                   cat:["Puzzle"],                      desc:"Slide letters to form words",                      src:"https://ubg98.github.io/WordSlide/" },
  { slug:"wood-block-puzzle",          name:"Wood Block Puzzle",            cat:["Puzzle","Strategy"],           desc:"Classic wooden block fitting puzzle",              src:"https://ubg98.github.io/WoodBlockPuzzle/" },
  { slug:"1010-color-match",           name:"1010 Color Match",             cat:["Puzzle","Strategy"],           desc:"Match colors in this 1010 puzzle",                 src:"https://ubg98.github.io/1010ColorMatch/" },
  { slug:"idle-breakout",              name:"Idle Breakout",                cat:["Puzzle","Simulation"],         desc:"Idle brick-breaking upgrade game",                 src:"https://ubg98.github.io/IdleBreakout/" },
  { slug:"freecell-solitaire",         name:"Freecell Solitaire",           cat:["Puzzle","Strategy"],           desc:"Classic freecell card game",                       src:"https://ubg98.github.io/FreecellSolitaire/" },
  { slug:"klondike-solitaire",         name:"Klondike Solitaire",           cat:["Puzzle","Strategy"],           desc:"Classic klondike card solitaire",                  src:"https://ubg98.github.io/KlondikeSolitaire/" },
  { slug:"spider-solitaire",           name:"Spider Solitaire",             cat:["Puzzle","Strategy"],           desc:"Classic spider card solitaire",                    src:"https://ubg98.github.io/SpiderSolitaire/" },
  { slug:"checkers-legend",            name:"Checkers Legend",              cat:["Puzzle","Strategy"],           desc:"Classic checkers board game",                      src:"https://ubg98.github.io/CheckersLegend/" },
  { slug:"tank-trouble",               name:"Tank Trouble",                 cat:["Action","Strategy"],           desc:"Multiplayer maze tank battle",                     src:"https://ubg98.github.io/TankTrouble/" },
  { slug:"pudding-monsters",           name:"Pudding Monsters",             cat:["Puzzle","Strategy"],           desc:"Slide puddings to merge them",                     src:"https://ubg98.github.io/PuddingMonsters/" },
  { slug:"circloo",                    name:"Circloo",                      cat:["Puzzle","Arcade"],             desc:"Roll inside the circle puzzle",                    src:"https://ubg98.github.io/Circloo/" },
  { slug:"circloo-2",                  name:"Circloo 2",                    cat:["Puzzle","Arcade"],             desc:"More rolling circle challenges",                   src:"https://ubg98.github.io/Circloo2/" },
  { slug:"block-the-pig",              name:"Block The Pig",                cat:["Puzzle","Strategy"],           desc:"Trap the pig before it escapes",                   src:"https://ubg98.github.io/BlockThePig/" },

  // ── SIMULATION & IDLE ─────────────────────────────────────
  { slug:"cookie-clicker-2",           name:"Cookie Clicker 2",             cat:["Simulation"],                  desc:"Addictive idle cookie clicker",                    src:"https://ubg98.github.io/CookieClicker2/" },
  { slug:"pou",                        name:"Pou",                          cat:["Simulation","Arcade"],         desc:"Feed and care for your pet Pou",                   src:"https://ubg98.github.io/Pou/" },
  { slug:"idle-mining-empire",         name:"Idle Mining Empire",           cat:["Simulation"],                  desc:"Build your idle mining empire",                    src:"https://ubg98.github.io/IdleMiningEmpire/" },
  { slug:"idle-restaurants",           name:"Idle Restaurants",             cat:["Simulation"],                  desc:"Build your restaurant empire",                     src:"https://ubg98.github.io/IdleRestaurants/" },
  { slug:"clicker-heroes",             name:"Clicker Heroes",               cat:["Simulation"],                  desc:"Click to defeat monsters and level up",            src:"https://ubg98.github.io/ClickerHeroes/" },
  { slug:"space-bar-clicker",          name:"Space Bar Clicker",            cat:["Simulation","Arcade"],         desc:"Click the space bar as fast as you can",           src:"https://ubg98.github.io/SpaceBarClicker/" },
  { slug:"minecraft-case-simulator",   name:"Minecraft Case Simulator",     cat:["Simulation"],                  desc:"Open Minecraft loot cases",                        src:"https://ubg98.github.io/MinecraftCase/" },

  // ── MORE GAMES ────────────────────────────────────────────
  { slug:"chicken-merge",              name:"Chicken Merge",                cat:["Action","Strategy"],           desc:"Merge chickens to build an army",                  src:"https://ubg98.github.io/ChickenMerge/" },
  { slug:"geometry-jump",              name:"Geometry Jump",                cat:["Action","Arcade"],             desc:"Rhythm-based geometry platformer",                 src:"https://ubg98.github.io/GeometryJump/" },
  { slug:"doodle-jump",                name:"Doodle Jump",                  cat:["Arcade","Action"],             desc:"Jump as high as you can on platforms",             src:"https://ubg98.github.io/DoodleJump/" },
  { slug:"crossy-road",                name:"Crossy Road",                  cat:["Arcade","Action"],             desc:"Cross roads and rivers endlessly",                 src:"https://ubg98.github.io/CrossyRoad/" },
  { slug:"pacman-html5",               name:"Pac-Man",                      cat:["Arcade"],                      desc:"Classic Pac-Man arcade game",                      src:"https://ubg98.github.io/PacMan/" },
  { slug:"cubefield",                  name:"Cubefield",                    cat:["Arcade","Action"],             desc:"Dodge cubes in this fast-paced game",              src:"https://ubg98.github.io/Cubefield/" },
  { slug:"bottle-flip",                name:"Bottle Flip",                  cat:["Arcade","Action"],             desc:"Flip the bottle to land it perfectly",             src:"https://ubg98.github.io/BottleFlip/" },
  { slug:"hop-pop-it",                 name:"Hop Pop It",                   cat:["Arcade","Action"],             desc:"Pop it and hop along",                             src:"https://ubg98.github.io/HopPopIt/" },
  { slug:"swingo",                     name:"Swingo",                       cat:["Arcade","Action"],             desc:"Swing your way through obstacles",                 src:"https://ubg98.github.io/Swingo/" },
  { slug:"turn-turn",                  name:"Turn Turn",                    cat:["Puzzle","Arcade"],             desc:"Turn and match in this tricky game",               src:"https://ubg98.github.io/TurnTurn/" },
  { slug:"tiny-fishing",               name:"Tiny Fishing",                 cat:["Simulation","Arcade"],         desc:"Cast and catch fish to upgrade your gear",         src:"https://ubg98.github.io/TinyFishing/" },
  { slug:"happy-fishing",              name:"Happy Fishing",                cat:["Simulation","Arcade"],         desc:"Relaxing fishing adventure",                       src:"https://ubg98.github.io/HappyFishing/" },
  { slug:"fishing-frenzy",             name:"Fishing Frenzy",               cat:["Simulation","Arcade"],         desc:"Catch fish in a frenzy",                           src:"https://ubg98.github.io/FishingFrenzy/" },
  { slug:"fishing-and-lines",          name:"Fishing And Lines",            cat:["Puzzle","Arcade"],             desc:"Draw lines to guide fish",                         src:"https://ubg98.github.io/FishingLines/" },
  { slug:"fish-eat-fish",              name:"Fish Eat Fish",                cat:["Action","Arcade"],             desc:"Eat smaller fish to grow bigger",                  src:"https://ubg98.github.io/FishEatFish/" },
  { slug:"among-us",                   name:"Among Us",                     cat:["Action","Simulation"],         desc:"Find the impostor in the crew",                    src:"https://ubg98.github.io/AmongUs/" },
  { slug:"five-nights-at-freddys",     name:"Five Nights at Freddy's",      cat:["Action","Simulation"],         desc:"Survive five nights at Freddy's",                  src:"https://ubg98.github.io/FNAF/" },
  { slug:"five-nights-at-freddys-2",   name:"Five Nights at Freddy's 2",    cat:["Action","Simulation"],         desc:"More terrifying nights at Freddy's",               src:"https://ubg98.github.io/FNAF2/" },
  { slug:"five-nights-at-freddys-3",   name:"Five Nights at Freddy's 3",    cat:["Action","Simulation"],         desc:"Fazbear's Fright horror nights",                   src:"https://ubg98.github.io/FNAF3/" },
  { slug:"five-nights-at-freddys-4",   name:"Five Nights at Freddy's 4",    cat:["Action","Simulation"],         desc:"Nightmare animatronics await",                     src:"https://ubg98.github.io/FNAF4/" },
  { slug:"five-nights-at-freddys-5",   name:"Five Nights at Freddy's 5",    cat:["Action","Simulation"],         desc:"Sister location horror nights",                    src:"https://ubg98.github.io/FNAF5/" },
  { slug:"age-of-war",                 name:"Age of War",                   cat:["Strategy","Action"],           desc:"Evolve your army through the ages",                src:"https://ubg98.github.io/AgeOfWar/" },
  { slug:"awesome-tanks",              name:"Awesome Tanks",                cat:["Action","Shooting"],           desc:"Destroy enemy tanks in this shooter",              src:"https://ubg98.github.io/AwesomeTanks/" },
  { slug:"awesome-tanks-2",            name:"Awesome Tanks 2",              cat:["Action","Shooting"],           desc:"More awesome tank destruction",                    src:"https://ubg98.github.io/AwesomeTanks2/" },
  { slug:"big-tower-tiny-square",      name:"Big Tower Tiny Square",        cat:["Adventure","Action"],          desc:"Climb the giant tower as a tiny square",           src:"https://ubg98.github.io/BigTowerTinySquare/" },
  { slug:"climb-over-it",              name:"Climb Over It",                cat:["Action","Adventure"],          desc:"Climb over everything in your way",                src:"https://ubg98.github.io/ClimbOverIt/" },
  { slug:"ovo",                        name:"OvO",                          cat:["Action","Arcade"],             desc:"Parkour platformer with style",                    src:"https://ubg98.github.io/OvO/" },
  { slug:"red-ball-4",                 name:"Red Ball 4",                   cat:["Adventure","Action"],          desc:"Roll the red ball to save the world",              src:"https://ubg98.github.io/RedBall4/" },
  { slug:"rabbit-samurai-2",           name:"Rabbit Samurai 2",             cat:["Action","Adventure"],          desc:"Swing and slice as a rabbit samurai",              src:"https://ubg98.github.io/RabbitSamurai2/" },
  { slug:"save-the-doge",              name:"Save The Doge",                cat:["Puzzle","Action"],             desc:"Protect the doge from bees",                       src:"https://ubg98.github.io/SaveTheDoge/" },
  { slug:"sling-tomb",                 name:"Sling Tomb",                   cat:["Action","Puzzle"],             desc:"Slingshot through ancient tombs",                  src:"https://ubg98.github.io/SlingTomb/" },
  { slug:"tower-crash-3d",             name:"Tower Crash 3D",               cat:["Action","Arcade"],             desc:"Crash through towers in 3D",                       src:"https://ubg98.github.io/TowerCrash3D/" },
  { slug:"toy-defense",                name:"Toy Defense",                  cat:["Strategy","Action"],           desc:"Defend with toy soldiers",                         src:"https://ubg98.github.io/ToyDefense/" },
  { slug:"traffic-control",            name:"Traffic Control",              cat:["Puzzle","Strategy"],           desc:"Direct traffic to prevent crashes",                src:"https://ubg98.github.io/TrafficControl/" },
  { slug:"traffic-tom",                name:"Traffic Tom",                  cat:["Action","Arcade"],             desc:"Tom races through crazy traffic",                  src:"https://ubg98.github.io/TrafficTom/" },
  { slug:"racing-monster-trucks",      name:"Racing Monster Trucks",        cat:["Racing","Action"],             desc:"Race massive monster trucks",                      src:"https://ubg98.github.io/MonsterTrucks/" },
  { slug:"park-out",                   name:"Park Out",                     cat:["Puzzle","Racing"],             desc:"Park your car without hitting anything",           src:"https://ubg98.github.io/ParkOut/" },
  { slug:"parking-fury",               name:"Parking Fury",                 cat:["Puzzle","Racing"],             desc:"Park your car in tight spaces",                    src:"https://ubg98.github.io/ParkingFury/" },
  { slug:"parking-fury-2",             name:"Parking Fury 2",               cat:["Puzzle","Racing"],             desc:"More parking challenges at night",                 src:"https://ubg98.github.io/ParkingFury2/" },
  { slug:"parking-fury-3",             name:"Parking Fury 3",               cat:["Puzzle","Racing"],             desc:"Night city parking challenges",                    src:"https://ubg98.github.io/ParkingFury3/" },
  { slug:"bus-parking-3d",             name:"Bus Parking 3D",               cat:["Puzzle","Racing"],             desc:"Park a huge bus in tight spots",                   src:"https://ubg98.github.io/BusParking3D/" },
  { slug:"wheelie-bike",               name:"Wheelie Bike",                 cat:["Racing","Action"],             desc:"Pop wheelies on your bike",                        src:"https://ubg98.github.io/WheelieBike/" },
  { slug:"biker-street",               name:"Biker Street",                 cat:["Racing","Action"],             desc:"Race through busy city streets",                   src:"https://ubg98.github.io/BikerStreet/" },
  { slug:"car-rush",                   name:"Car Rush",                     cat:["Racing","Arcade"],             desc:"Rush through traffic in your car",                 src:"https://ubg98.github.io/CarRush/" },
  { slug:"fire-truck",                 name:"Fire Truck",                   cat:["Racing","Action"],             desc:"Drive the fire truck to save the day",             src:"https://ubg98.github.io/FireTruck/" },
  { slug:"adventure-drivers",          name:"Adventure Drivers",            cat:["Racing","Adventure"],          desc:"Drive through crazy adventure tracks",              src:"https://ubg98.github.io/AdventureDrivers/" },
  { slug:"8-ball-pool",                name:"8 Ball Pool",                  cat:["Sports","Strategy"],           desc:"Classic 8 ball pool billiards",                    src:"https://ubg98.github.io/8BallPool/" },
  { slug:"basket-and-ball",            name:"Basket and Ball",              cat:["Sports","Puzzle"],             desc:"Bounce the ball into the basket",                  src:"https://ubg98.github.io/BasketAndBall/" },
  { slug:"basket-random",              name:"Basket Random",                cat:["Sports","Arcade"],             desc:"Wacky random basketball game",                     src:"https://ubg98.github.io/BasketRandom/" },
  { slug:"basket-champs",              name:"Basket Champs",                cat:["Sports","Arcade"],             desc:"Be the basketball champion",                       src:"https://ubg98.github.io/BasketChamps/" },
  { slug:"ball-sort-soccer",           name:"Ball Sort Soccer",             cat:["Sports","Puzzle"],             desc:"Sort soccer balls by color",                       src:"https://ubg98.github.io/BallSortSoccer/" },
  { slug:"ballistic",                  name:"Ballistic",                    cat:["Action","Shooting"],           desc:"Fire projectiles to destroy targets",              src:"https://ubg98.github.io/Ballistic/" },
  { slug:"blumgi-rocket",              name:"Blumgi Rocket",                cat:["Action","Arcade"],             desc:"Launch and bounce your rocket",                    src:"https://ubg98.github.io/BlumgiRocket/" },
  { slug:"bomb-it-6",                  name:"Bomb It 6",                    cat:["Action","Arcade"],             desc:"Bomb your enemies in the maze",                    src:"https://ubg98.github.io/BombIt6/" },
  { slug:"bomb-it-7",                  name:"Bomb It 7",                    cat:["Action","Arcade"],             desc:"More explosive bombing action",                    src:"https://ubg98.github.io/BombIt7/" },
  { slug:"bubble-pop-adventures",      name:"Bubble Pop Adventures",        cat:["Puzzle","Arcade"],             desc:"Pop bubbles in this colorful adventure",           src:"https://ubg98.github.io/BubblePop/" },
  { slug:"dinosaurs-merge-master",     name:"Dinosaurs Merge Master",       cat:["Strategy","Simulation"],       desc:"Merge dinosaurs to build your army",               src:"https://ubg98.github.io/DinosaursMerge/" },
  { slug:"fruita-crush",               name:"Fruita Crush",                 cat:["Puzzle","Arcade"],             desc:"Crush fruits in this match-3 game",                src:"https://ubg98.github.io/FruitaCrush/" },
  { slug:"gobdun",                     name:"Gobdun",                       cat:["Adventure","Action"],          desc:"Dungeon adventure with goblins",                   src:"https://ubg98.github.io/Gobdun/" },
  { slug:"guess-the-kitty",            name:"Guess The Kitty",              cat:["Puzzle","Arcade"],             desc:"Guess which kitty is hiding",                      src:"https://ubg98.github.io/GuessTheKitty/" },
  { slug:"icy-purple-head-2",          name:"Icy Purple Head 2",            cat:["Adventure","Puzzle"],          desc:"Slide on ice to reach the goal",                   src:"https://ubg98.github.io/IcyPurpleHead2/" },
  { slug:"icy-purple-head-3",          name:"Icy Purple Head 3",            cat:["Adventure","Puzzle"],          desc:"More icy sliding puzzle levels",                   src:"https://ubg98.github.io/IcyPurpleHead3/" },
  { slug:"mr-bullet-3d",               name:"Mr Bullet 3D",                 cat:["Shooting","Puzzle"],           desc:"3D physics shooting puzzles",                      src:"https://ubg98.github.io/MrBullet3D/" },
  { slug:"ninja-cat-exploit",          name:"Ninja Cat",                    cat:["Action","Adventure"],          desc:"Ninja cat slices through enemies",                 src:"https://ubg98.github.io/NinjaCat/" },
  { slug:"roper",                      name:"Roper",                        cat:["Action","Arcade"],             desc:"Rope your way through obstacles",                  src:"https://ubg98.github.io/Roper/" },
  { slug:"stick-merge",                name:"Stick Merge",                  cat:["Action","Shooting"],           desc:"Merge sticks to fight enemies",                    src:"https://ubg98.github.io/StickMerge/" },
  { slug:"tri-peaks-solitaire",        name:"Tri Peaks Solitaire",          cat:["Puzzle","Strategy"],           desc:"Clear three peaks in solitaire",                   src:"https://ubg98.github.io/TriPeaksSolitaire/" },
  { slug:"adam-and-eve-51",            name:"Adam And Eve 5 Part 1",        cat:["Adventure","Puzzle"],          desc:"Prehistoric point and click adventure",            src:"https://ubg98.github.io/AdamEve51/" },
  { slug:"adam-and-eve-52",            name:"Adam And Eve 5 Part 2",        cat:["Adventure","Puzzle"],          desc:"Continue the prehistoric adventure",               src:"https://ubg98.github.io/AdamEve52/" },
  { slug:"adam-and-eve-6",             name:"Adam And Eve 6",               cat:["Adventure","Puzzle"],          desc:"Adam's prehistoric adventure continues",           src:"https://ubg98.github.io/AdamEve6/" },
];

window.CATEGORIES = [
  { name:"Home",       icon:"fa-house",        link:"index.html"                  },
  { name:"Action",     icon:"fa-bolt",         link:"category.html?cat=Action"    },
  { name:"Racing",     icon:"fa-car",          link:"category.html?cat=Racing"    },
  { name:"Sports",     icon:"fa-trophy",       link:"category.html?cat=Sports"    },
  { name:"Adventure",  icon:"fa-map",          link:"category.html?cat=Adventure" },
  { name:"Puzzle",     icon:"fa-puzzle-piece", link:"category.html?cat=Puzzle"    },
  { name:"Simulation", icon:"fa-rocket",       link:"category.html?cat=Simulation"},
  { name:"All Games",  icon:"fa-th",           link:"category.html"               },
];
